### ISSUE TITLE
Support Apple?

### ISSUE THREAD

**Issue by ranocha** [IANW-Projects/toolkitICL#12]
This came up in #11: Do we want to support OS X officially or at least as far as we can?

Pros:
- Many people like to use it.
- We can also run tests on OS X using Travis, possibly catching subtle bugs induced by the OS etc.

Cons/TODOs:
- I don't have access to a computer running OS x :wink: Hence, it's a bit difficult for me to get everything done correctly and test it.
- We would have to adapt many parts to an additional OS, e.g. `getOS`.
- We need to set up Travis for OS X. Right now, the main problem seems to be getting a working `cl2.hpp`
  https://github.com/IANW-Projects/toolkitICL/blob/ae26c3cd203aa8dcb6290b6a331b993581fcb5ca/.travis.yml#L40
  Edit: cf. https://rageandqq.github.io/blog/2018/03/09/opencl-mac-cpp.html

CC: @philipheinisch @Kostaszki

**Comment by philipheinisch** [comment]
I could try and set up a development OS X VM. It seems like there are indeed a few scientists using Apple products. It could also be interesting for MatCL.

**Comment by ranocha** [comment]
In general, I'm in favour of trying to support OS X. If we had some local setup running to make it work, that would be perfect.

**Comment by ranocha** [comment]
Closed in #14.

**Comment by fantasyRqg** [comment]
I can help you to test , with Amd graphic card

**Comment by philipheinisch** [comment]
Thanks! Feel free to test the latest version, we are happy to hear your feedback.
