### ISSUE TITLE
Compiler Flags

### ISSUE THREAD

**Issue by ranocha** [IANW-Projects/toolkitICL#15]
Do we really want to set all the compiler flags of https://github.com/IANW-Projects/toolkitICL/blob/acb8f5df593f2f041f819e764869d8374a2d9875/CMakeLists.txt#L30
In particular, options such as `-mavx2` are problematic if the target CPU does not support them. This caused some errors while enabling Mac OS X in #14.

Some reasons for the current choice are probably connected with clusters, where build machines have not the same architecture as the compute nodes. But this could be caught by some other variables passed to cmake. What is your opinion, @philipheinisch?

**Comment by philipheinisch** [comment]
Good question, one solution would be to automatically detect CPU features and enable appropriate flags automatically – but this could cause problems on compute clusters. Interestingly GCC just ignored unsupported flags for example on ARM. Maybe an internal lookup table for different CPU architectures?

**Comment by ranocha** [comment]
That might be possible but sounds rather complicated.

**Comment by ranocha** [comment]
We will check whether the host code is performance critical (probably it is not) and adapt the compiler flags accordingly, e.g. by setting only `-march=native`.

**Comment by ranocha** [comment]
Closed in #30.
