### ISSUE TITLE
Add OpenCL platform?

### ISSUE THREAD

**Issue by philipheinisch** [IANW-Projects/toolkitICL#6]
Based on the [suggestion](https://github.com/IANW-Projects/toolkitICL/pull/3#issuecomment-462120690) by @ranocha: Does it make sense so add the OpenCL platform name to the HDF5 output?

Does the platform name provide any more information compared to device name and OpenCL version? Or should we maybe implement a new structure, that joins all the necessary information in a single HDF5 struct or string?

**Comment by ranocha** [comment]
I think it would be a bit more clear which platform is used, e.g. POCL, Intel Runtime, Nvidia etc. It can also be derived from the deice name and OpenCL version, but some additional redundancy is often good to avoid confusion. For me, these three pieces of information would be enough and an additional struct would not be necessary.

**Comment by philipheinisch** [comment]
Ok, than I will add the feature.
