### ISSUE TITLE
Make the test build optional?

### ISSUE THREAD

**Issue by philipheinisch** [IANW-Projects/toolkitICL#9]
Based on the the discussion in PR #8, it might be a good idea to make the test build optional. Using something like '-DTESTS=ON' (as suggested by @ranocha ) with cmake would only include the tests, if explicitly specified by the user. This is also the way I'm used to from other projects. What do you think @Kostaszki and @ranocha?

**Comment by ranocha** [comment]
Having optional test would be good. We could possibly speed up the build process of the tests. Right now, `hdf5_io.o` is compiled for every test file while it would suffice to compile it only once.
